import{S as u,A as f}from"./assets/vendor-584ac928.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const l=new u(".swiper",{preventInteractionOnTransition:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});var d=document.querySelector(".swiper-button-prev"),p=document.querySelector(".swiper-button-next");d.disabled=!0;d.addEventListener("click",function(){l.slidePrev()});p.addEventListener("click",function(){l.slideNext()});l.on("slideChange",function(){p.disabled=!!l.isEnd,d.disabled=!!l.isBeginning});let c,a;c=document.querySelector(".swiper-button-prev-review");a=document.querySelector(".swiper-button-next-review");document.addEventListener("DOMContentLoaded",async()=>{try{const n=await(await fetch("https://portfolio-js.b.goit.study/api/reviews")).json();Array.isArray(n)&&n.length>0?w(n):v()}catch(i){console.error("Error fetching data:",i)}const t=new u(".swiper-container",{direction:"horizontal",slidesPerView:"auto",spaceBetween:16,pagination:{el:".swiper-pagination"},navigation:{nextEl:".swiper-button-next-review",prevEl:".swiper-button-prev-review"}});t.on("slideChange",()=>{t.isBeginning?(c.disabled=!0,a.disabled=!1):t.isEnd?(c.disabled=!1,a.disabled=!0):(c.disabled=!1,a.disabled=!1),t.update()}),c.addEventListener("click",function(){t.slidePrev()}),a.addEventListener("click",function(){t.slideNext()})});function w(t){const i=document.querySelector(".reviews-list");if(!i){console.error("Review container not found.");return}const n=t.map(({_id:o,author:e,avatar_url:r,review:s})=>`<li class="reviews-item swiper-slide">
      <div class="reviews-item-box">
        <img
          sizes="(min-width: 1440px) 72px, (min-width: 768px) 72px, (min-width: 375px) 72px"
          src="${r}"
          alt="${e}"
          class="reviews-item-img"
          width="48"
          height="48"
        />
        <h3 class="reviews-item-title">${e}</h3>
        <p class="reviews-item-desc">${s}</p>
      </div>
    </li>`).join("");i.innerHTML=n}function v(){const t=document.querySelector(".reviews-list");if(!t){console.error("Review container not found.");return}t.innerHTML="<p>No reviews found</p>"}const m=new f(".accordion-container",{showMultiple:!0}),g=document.querySelectorAll(".faq-item");g.forEach(t=>{const i=t.querySelector(".ac-header"),n=t.querySelector(".ac-trigger"),o=t.querySelector(".ac-text");i.addEventListener("click",()=>{o.classList.contains("active")?m.close(o):n.click()})});
//# sourceMappingURL=commonHelpers.js.map
